version: "3"

services:
  server:
    build: .
    container_name: "${APP_NAME}"
    volumes:
      - ".:/app"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: "uvicorn main:app --host 0.0.0.0 --port ${APP_PORT} --reload"
